automatic push and push --tags; version management in dynamic post-commit

diff --git a/lint b/lint
--- a/lint
+++ b/lint
@@ -45,8 +45,13 @@ xenon --max-absolute B --max-modules A --max-average A $mod
 if [ $? -ne 0 ]; then { echo "Failed, aborting." ; exit 1; } fi
 
 cat > ./.git/hooks/post-commit<< EOF
-printf "Tagging version %s" "$VERSION"
+printf "git push"
+git push
+printf "git tag %s" "$VERSION"
 git tag "$VERSION"
+if [ $? -ne 0 ]; then { printf "Error tagging version %s" "$VERSION" ; } fi
+printf "git push --tags"
+git push --tags
 if [ $? -ne 0 ]; then { printf "Error tagging version %s" "$VERSION" ; } fi
 EOF
 chmod +x ./.git/hooks/post-commit
