versioning fixes

diff --git a/lint b/lint
--- a/lint
+++ b/lint
@@ -7,8 +7,8 @@ mod=${1:-./src}
 # mod=${mod//\./\/}
 
 echo "Verifying version change $mod ..."
-python3 -m src.version
-if [ $? -ne 0 ]; then { echo "Failed, aborting." ; exit 1; } fi
+VERSION=$(python3 -m src.version)
+if [ $? -ne 0 ]; then { printf "Failed, aborting. %s" "$VERSION" ; exit 1; } fi
 
 echo "Formatting code (autopep) $mod ..."
 autopep8 --in-place --aggressive --aggressive --recursive .
@@ -45,4 +45,8 @@ if [ $? -ne 0 ]; then { echo "Warning." ; } fi
 xenon --max-absolute B --max-modules A --max-average A $mod
 if [ $? -ne 0 ]; then { echo "Failed, aborting." ; exit 1; } fi
 
-echo "Done."
+printf "Tagging version %s" "$VERSION"
+git tag "$VERSION"
+if [ $? -ne 0 ]; then { printf "Error tagging version %s" "$VERSION" ; } fi
+
+echo "\nDone."
